### ISSUE TITLE
글작성이 안됩니다.

### ISSUE THREAD

**Issue by dmzvillager** [bjrambo/xe-module-schedule#6]
apache 2.4.12, php 5.6.8 xe 1.8.1을 사용 중입니다. 글 작성이 안됩니다.

**Comment by bjrambo** [comment]
해당 서버에서 테스트 해봐야할 것 같습니다.(새로 설치한서버에서는 문제없음..) 
계정 정보를 qw5414@naver.com 으로 주시고 FTP와 웹사이트 어드민 계정을 주시면 확인해볼께요.

**Comment by dmzvillager** [comment]
apache 2.4.12, php 5.6.8 xe 1.8.1을 사용 중이고, 
에러 로그입니다.
[Wed May 13 19:16:46.168317 2015] [:error] [pid 3275:tid 139871104526080] [client 192.168.0.1:57013] PHP Deprecated:  Automatically populating $HTTP_RAW_POST_DATA is deprecated and will be removed in a future version. To avoid this warning set 'always_populate_raw_post_data' to '-1' in php.ini and use the php://input stream instead. in Unknown on line 0, referer: http://127.0.0.1/index.php?mid=m_schedule&act=dispScheduleInsert&selected_date=20150501
[Wed May 13 19:16:46.168453 2015] [:error] [pid 3275:tid 139871104526080] [client 192.168.0.1:57013] PHP Warning:  Cannot modify header information - headers already sent in Unknown on line 0, referer: http://127.0.0.1/index.php?mid=m_schedule&act=dispScheduleInsert&selected_date=20150501
[Wed May 13 19:17:02.537737 2015] [:error] [pid 3275:tid 139871096133376] [client 192.168.0.1:57019] PHP Deprecated:  Automatically populating $HTTP_RAW_POST_DATA is deprecated and will be removed in a future version. To avoid this warning set 'always_populate_raw_post_data' to '-1' in php.ini and use the php://input stream instead. in Unknown on line 0, referer: http://127.0.0.1/index.php?mid=m_schedule&act=dispScheduleInsert&selected_date=20150501
[Wed May 13 19:17:02.537903 2015] [:error] [pid 3275:tid 139871096133376] [client 192.168.0.1:57019] PHP Warning:  Cannot modify header information - headers already sent in Unknown on line 0, referer: http://127.0.0.1/index.php?mid=m_schedule&act=dispScheduleInsert&selected_date=20150501

**Comment by bjrambo** [comment]
@dmzvillager 서버환경이 단순히 windows에서 돌리시는것인가요? 아니면 웹호스팅에서 돌리시는 것인가요?

그리고 127.0.0,1 으로 주소가 잡히는것으로 보아.. 기본URL의오류일것 같기도한데요..그렇게 된다면.. 모듈의 문제점이라고 볼 수 없을 수도 있습니다..

**Comment by dmzvillager** [comment]
ver 0.1 을 설치 하고, ver 1.1을 업데이트 하니 글작성이 됩니다. 누락된 파일이 있는건 아닐까요?

**Comment by bjrambo** [comment]
@dmzvillager 아니요.. 문제있다고 적은 곳에도 애초에 1.1이고.. 1.0 배포당시에도 문제점은 발견되지 않았는데요..;;
